### ISSUE TITLE
API file configuration

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#194]
Currently, all the configurations that can be done for the API are done through environment variables. It works fine but it could be tricky to create more complex configuration options like tree-like ones.

One example is to disable some background tasks or modify their frequency. Nowadays, it is just possible to disable them all by using a flag, but nothing more. Then, with a config file, we could do this:

```yaml
BACKGROUND_TASKS:
    TASK_POPGRPH:
        ENABLED: False
    TASK_POPDET:
        ENABLED: True
        INTERVAL: 30 # in minutes
```

This will unlock more customization possibilities for the user and is a requirement to secure API runners in this PR https://github.com/BSC-ES/autosubmit-api/pull/192
