### ISSUE TITLE
Extracting CPMIP metrics for Climate DT experiments

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#28]
In GitLab by @mcastril on Aug 4, 2023, 15:30

We are trying to get CPMIP information from frontier AS4 experiments using the minimal configuration and with a "non-standard" job structure (no other CHUNK-based remote jobs than SIM ones). 

I'll report here the steps taken and we'll see if there's anything missing in the Performance View.

CC @kinow @rohanali1798 @dbeltrankyl

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 15:35

As a first step, I copy the necessary experiment files to `bscesautosubmitdev01`. These files are detailed in https://earth.bsc.es/gitlab/es/autosubmitreact/-/blob/master/deployment/scripts/copy_send.sh

I'm not using the script since I don't have a direct connection from the VM to the AS GUI development environment. I did a tar.gz of those files, and I transferred them through a third host.

I'm taking experiments a06x (control) and a07p (historical)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 15:36

```
drwxrwxr-x 8 rocky rocky     78 jul  7 15:30 a06x
drwxr-xr-x 9 rocky rocky     91 jul 27 15:16 a07p
-rwxrwxr-- 1 rocky rocky 360448 ago  1 10:26 job_data_a06x.db
-rw-rw-r-- 1 rocky rocky 293185 ago  1 10:26 job_data_a06x.sql
-rwxrwxr-- 1 rocky rocky 122880 ago  1 12:47 job_data_a07p.db
-rw-rw-r-- 1 rocky rocky  97907 ago  1 12:47 job_data_a07p.sql
-rw-rw---- 1 rocky rocky  28672 jul 24 17:03 structure_a06x.db
-rw-rw---- 1 rocky rocky  65536 jul 25 18:22 structure_a07p.db
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 15:37

Then, I deploy the experiment directories in `development/autosubmit` and the databases in `development/autosubmit/as_metadata/data` and `development/autosubmit/as_metadata/structures`

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 15:40

Second step, try to use the API to get the minimal information. 

With https://bscesautosubmitdev01.bsc.es/autosubmitapi/expinfo/a07p I get the following error:

"Required file not found /home/rocky/development/autosubmit/a07p/conf/autosubmit_a07p.conf"

It looks like the API is not able to extract the information from the `minimal.yml` and `main.yml`

Same happens with a06x

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 15:44

Taking an AS4 experiment upgraded from AS3, I create the classical configuration files, and I populate them with the information provided in `main.yml` and `minimal.yml`

Now the https://bscesautosubmitdev01.bsc.es/autosubmitapi/expinfo/a06x call output looks better and there are no errors.

I try the performance endpoint but this is the response:

```
ASYPD	0
CHSY	15.3057
JPSY	0
Parallelization	1
RSYPD	0
SYPD	0
```

There is correct information from all the SIM jobs (SYPD, ASYPD, CHSY), so something is going wrong with the averaging of the SYPD.

Additionally, the following warnings:

| 14 | "We couldn't find COMPLETED POST jobs in the experiment. ASYPD can't be calculated."                    |

| 15 | "RSYPD | There are no TRANSFER nor CLEAN (COMPLETED) jobs in the experiment, RSYPD cannot be computed." |

We truly need some TRANSFER job to compute the RSYPD

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 15:54

I had some missing information in the `expdef` and `jobs` configurations. The API could not get the simulated time per chunk, for example. After populating these fields, it looks better.

|                 |         |
|-----------------|---------|
| ASYPD           | 0.7443  |
| CHSY            | 15.3057 |
| JPSY            | 0       |
| Parallelization | 1       |
| RSYPD           | 0       |
| SYPD            | 1.568   |

However, CHSY is still unrealistic, and this must be because the PROCESSORS information lives is in the `proj` (distributed configuration), so have also to propagate this one.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @rohanali1798 on Aug 4, 2023, 16:24

@mcastril These performance metrics parameters will also be used in the testing_suite if we create the performance VIEW in the DDBB and populate it by API?? or this is just for React web app (GUI)?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 16:26

It seems that the value declared in the `jobs.yml` is irrelevant, and actually now I think that these data should be taken from the DDBB, but somehow is not being taken.

`sqlite> select job_name,ncpus,nnodes from job_data;`

```
a06x_19500101_fc0_1_SIM|30720|240
a06x_19500101_fc0_1_SIM|61440|240
a06x_19500101_fc0_2_SIM|61440|240
a06x_19500101_fc0_2_SIM|61440|240
a06x_19500101_fc0_3_SIM|61440|240
a06x_19500101_fc0_4_SIM|61440|240
a06x_19500101_fc0_5_SIM|61440|240
a06x_19500101_fc0_6_SIM|61440|240
a06x_19500101_fc0_7_SIM|61440|240
a06x_19500101_fc0_7_SIM|61440|240
a06x_19500101_fc0_7_SIM|61440|240
a06x_19500101_fc0_7_SIM|61440|240
a06x_19500101_fc0_7_SIM|61440|240
a06x_19500101_fc0_7_SIM|61440|240
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 16:28

The testing_suite can generate some metrics directly querying the Autosubmit DDBBs. But this, I think is only valid for experiments run with the testing_suite (or that are included in your test collection).

We need the API to get performance metrics from any experiment in the VM. And then we can also consume this data from the GUI, but we can also do it directly.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 16:32

After these tests, we have some issues with getting performance metrics from these experiments:

* API not compatible with the minimal/main configuration system (could be sorted out with some manual changes in the configuration)
* API cannot get the `ncpus` from the DDBB (strange). This prevents us from getting meaningful CHSY
* We don't have TRANSFER and CLEAN jobs in the workflow, so we cannot compute RSYPD (the value known as ASYPD externally) unless we introduce one of these jobs

So, by now we only would have SYPD

About the problem with the `ncpus`, one possible cause is that this experiment is using a different number of processors across the run. I don't remember how well the API could deal with this even if this was not the reason for reading always `ncpus: 1`.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 17:52

I had the idea to play with an experiment deployed in the production environment to see from where the API is getting the experiment information.

In experiment `a4db`: https://earth.bsc.es/autosubmitapp/experiment/a4db

I realized that the parallelization value is taken from the `jobs` configuration file. If I modify the number in the config the metrics are changed instantaneously (on reload).

So somehow it seems that the API/ConfigParser is not able to retrieve the values from my dev configuration:

```
 JOBS:
   SIM:
     PLATFORM: LUMI
     PROCESSORS: 128
```

I checked that the API is indeed reading that file, by commenting the SIM job (in that case the performance endpoint is not available)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 4, 2023, 18:55

I debugged the return of this call:

```
    def get_processors(self, section):
        return self._conf_parser.get_processors(section)
```

In https://earth.bsc.es/gitlab/es/autosubmit_api/-/blob/main/autosubmit_api/config/ymlConfigStrategy.py#L160

And it's returning 1. Do you remember some kind of bug in an older AutosubmitConfigParser @dbeltrankyl ? Do you think that it'd be a matter of updating it?

PS: The last thing I did on Friday was to update the AutosubmitConfigParser in the Dev VM.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 7, 2023, 15:49

`from autosubmitconfigparser.config.configcommon import AutosubmitConfig as Autosubmit4Config`

`self._conf_parser = Autosubmit4Config(expid)`

```python
    def get_processors(self, section):
        return self._conf_parser.get_processors(section)
```

The function seems to be only a wrapper of the `autosubmitconfigparser`. But I cannot imagine how it could read the wrong value. Any ideas?

https://earth.bsc.es/gitlab/es/autosubmit_api/-/blob/main/autosubmit_api/config/ymlConfigStrategy.py#L161

https://earth.bsc.es/gitlab/ces/autosubmit4-config-parser/-/blob/main/autosubmitconfigparser/config/configcommon.py#L223

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 7, 2023, 15:57

Ok, I didn't have so much time so I did something not really orthodox.

I hardcoded the return value of `get_processors` in `python3.7/site-packages/autosubmitconfigparser/config/configcommon.py` and the API request returns the hardcoded value.

So it's clear that `autosubmitconfigparser` is failing to read the PROCESSORS number.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Aug 7, 2023, 15:58

@dbeltrankyl please do you see something that I miss and is necessary to get the PROCESSORS key?

```
(base) [root@vm conf]# cat autosubmit_a06x.yml 
CONFIG:
  AUTOSUBMIT_VERSION: "4.0.0b0"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
MAIL:
  NOTIFICATIONS: False
STORAGE:
  TYPE: "pkl"
WRAPPERS:
  WRAPPER_0:
    TYPE: "vertical"
    JOBS_IN_WRAPPER: "SIM"


(base) [root@vm conf]# cat expdef_a06x.yml 
DEFAULT:
  EXPID: "a06x"
  HPCARCH: "LUMI"
#hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  CUSTOM_CONFIG: "%PROJDIR%/conf/bootstrap/"

EXPERIMENT:
  DATELIST: 19500101
  CHUNKSIZEUNIT: month
  CHUNKSIZE: 1
  NUMCHUNKS: 132

PROJECT:
  PROJECT_TYPE: "git"
  PROJECT_DESTINATION: "git_project"
GIT:
  PROJECT_ORIGIN: "https://earth.bsc.es/gitlab/digital-twins/de_340/workflow"
  PROJECT_BRANCH: "ifs-bundle"
  PROJECT_COMMIT: ""
  PROJECT_SUBMODULES: "ifs-nemo"
  FETCH_SINGLE_BRANCH: True


(base) [root@vm conf]# cat jobs_a06x.yml
JOBS:
  SIM:
   PROCESSORS: 3840 
   RUNNING: chunk
   WALLCLOCK: 2:50
    

(base) [root@vm conf]# cat platforms_a06x.yml 
PLATFORMS:
  LUMI:
    RESERVATION: "DT_264CPU"
    PARTITION: "standard"
    TYPE: slurm
    MAX_WALLCLOCK: "48:00"
    MAX_PROCESSORS: 28282
```
